<template>
  <div id="settings">
    <v-row>
      <v-col cols="12" sm="6" md="4">
        <v-card color="card">
          <v-card-title class="cardtext--text">Meeting Service</v-card-title>
          <v-card-text class="cardtext--text">
            The Meeting Service adds a button to the top bar on your website to
            allow your users to easily join a virtual meeting on a platform of
            your choice. The button will only be visible to users who are logged
            in. To get started, create a recurring meeting link with the service
            of your choice before enabling the service here.
            <v-switch
              v-model="privateSettings.useMeeting"
              label="Enable Meeting Service"
              color="secondary"
            />
            <v-expand-transition>
              <div v-if="privateSettings.useMeeting">
                <v-text-field
                  v-model="privateSettings.meetLink"
                  filled
                  label="Meeting Link"
                  hint="Copy and paste the meeting link generated by your virtual meeting platform."
                  color="secondary"
                />
              </div>
            </v-expand-transition>
          </v-card-text>
        </v-card>
      </v-col>
      <v-col cols="12" sm="6" md="4">
        <v-card color="card">
          <v-card-title class="cardtext--text">Calendar Service</v-card-title>
          <v-card-text class="cardtext--text">
            The Calendar Service uses Google Apps Script to interact with a
            Google Calendar that you own, allowing you to view and manage events
            through your website. To get started, create a Google Calendar and
            deploy the Calendar Service code as a web app on Google Apps Script
            before enabling the service here.
            <v-switch
              v-model="settings.useCalendar"
              label="Enable Calendar Service"
              color="secondary"
            />
            <v-expand-transition>
              <div v-if="settings.useCalendar">
                <v-text-field
                  v-model="settings.calURL"
                  filled
                  label="Script URL"
                  hint="Copy and paste the script URL generated by Google Apps Script."
                  color="secondary"
                />
                <v-text-field
                  v-model="settings.calID"
                  filled
                  label="Google Calendar ID"
                  hint="Copy and paste the calendar ID from Google Calendar."
                  color="secondary"
                />
                <v-select
                  v-model="settings.calView"
                  :items="permissions"
                  filled
                  label="Viewing Permissions"
                  hint="Choose who can view the calendar."
                  persistent-hint
                  color="secondary"
                  item-color="secondary"
                />
                <v-btn
                  block
                  color="secondary"
                  class="sectext--text"
                  @click="generatePassword('apps-script-cal-view')"
                >
                  Generate Password
                </v-btn>
                <v-spacer />
                <v-select
                  v-model="settings.calEdit"
                  :items="permissions"
                  filled
                  label="Editing Permissions"
                  hint="Choose who can add, edit, and remove calendar events."
                  persistent-hint
                  color="secondary"
                  item-color="secondary"
                />
                <v-btn
                  block
                  color="secondary"
                  class="sectext--text"
                  @click="generatePassword('apps-script-cal-edit')"
                >
                  Generate Password
                </v-btn>
              </div>
            </v-expand-transition>
          </v-card-text>
        </v-card>
      </v-col>
      <v-col cols="12" sm="6" md="4">
        <v-card color="card" class="slide">
          <v-card-title class="cardtext--text">Email Service</v-card-title>
          <v-card-text class="cardtext--text">
            The Email Service uses Google Apps Script to interact with a Gmail
            account, allowing you to send emails through your website. This
            service enables additional features on some components and is
            required for others to work properly. To get started, deploy the
            Email Service code as a web app on Google Apps Script before
            enabling the service here.
            <v-switch
              v-model="settings.useEmail"
              label="Enable Email Service"
              color="secondary"
            />
            <v-expand-transition>
              <div v-if="settings.useEmail">
                <v-text-field
                  v-model="settings.mailURL"
                  filled
                  label="Script URL"
                  hint="Copy and paste the URL generated by Google Apps Script."
                  color="secondary"
                />
                <v-select
                  v-model="settings.email"
                  :items="permissions"
                  filled
                  label="Email Service Permissions"
                  hint="Choose who can send emails through the website."
                  persistent-hint
                  color="secondary"
                  item-color="secondary"
                />
                <v-btn
                  block
                  color="secondary"
                  class="sectext--text"
                  @click="generatePassword('apps-script-mail')"
                >
                  Generate Password
                </v-btn>
                <v-spacer />
                <h3>Recipients</h3>
                <p class="mt-2">
                  Only the email addresses listed here will be available to use
                  when sending emails through your website via the email
                  service.
                </p>
                <v-expansion-panels class="mb-6" accordion>
                  <v-expansion-panel
                    v-for="(item, index) in privateSettings.addresses"
                    :key="index"
                  >
                    <v-expansion-panel-header class="cardtext--text"
                      >{{ item.text || `Recipient ${index + 1}` }}
                      <template #actions>
                        <v-icon color="cardtext">$expand</v-icon>
                      </template>
                    </v-expansion-panel-header>
                    <v-expansion-panel-content class="cardtext--text">
                      <v-text-field
                        v-model="item.text"
                        :label="`Recipient ${index + 1} Name`"
                        filled
                        color="secondary"
                      />
                      <v-text-field
                        v-model="item.value"
                        :label="`Email Address ${index + 1}`"
                        filled
                        color="secondary"
                      />
                      <v-btn
                        block
                        color="error"
                        class="errtext--text"
                        @click="removeEmailAddress(index)"
                        >Delete Recipient</v-btn
                      >
                    </v-expansion-panel-content>
                  </v-expansion-panel>
                </v-expansion-panels>
                <v-btn
                  block
                  color="secondary"
                  class="sectext--text"
                  @click="addEmailAddress"
                  >Add Recipient</v-btn
                >
              </div>
            </v-expand-transition>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script lang="ts" setup>
import { usePages } from "@/store/pages";
import { useSettings } from "@/store/settings";
import { onUnmounted } from "vue";
import type { FirestoreError } from "firebase/firestore/lite";
import { displayPageAlert, getFirestoreError } from "@/plugins/errorHandler";
import { settings, privateSettings } from "@/plugins/routerStoreHelpers";
import { permissions } from "@/plugins/authHandler";

const save = async (
  callback: () => void,
  err = (e: FirestoreError) => {
    displayPageAlert(`An error occurred while saving: ${getFirestoreError(e)}`);
  }
) => {
  try {
    const { firestore } = await import("@/plugins/firebase");
    const { doc, setDoc } = await import("firebase/firestore/lite");
    await setDoc(
      doc(firestore, "configuration/settings"),
      {
        calEdit: settings.value.calEdit || "",
        calID: settings.value.calID || "",
        calURL: settings.value.calURL || "",
        calView: settings.value.calView || "",
        email: settings.value.email || "",
        mailURL: settings.value.mailURL || "",
        useCalendar: settings.value.useCalendar || false,
        useEmail: settings.value.useEmail || false
      },
      {
        merge: true
      }
    );
    await setDoc(
      doc(firestore, "configuration/priv-settings"),
      {
        addresses: privateSettings.value.addresses || [],
        meetLink: privateSettings.value.meetLink || "",
        useMeeting: privateSettings.value.useMeeting || false
      },
      { merge: true }
    );
    callback();
  } catch (error) {
    err(error as FirestoreError);
  }
};

defineExpose({
  save
});

const addEmailAddress = () => {
  privateSettings.value.addresses.push({
    text: "",
    value: ""
  });
};

const removeEmailAddress = (index: number) => {
  if (privateSettings.value.addresses) {
    privateSettings.value.addresses.splice(index, 1);
  }
};

const generatePassword = async (type: string) => {
  try {
    const { generateString } = await import("@/plugins/stringGenerator");
    const password = generateString(20);
    const { firestore } = await import("@/plugins/firebase");
    const { doc, setDoc } = await import("firebase/firestore/lite");
    await setDoc(
      doc(firestore, `configuration/${type}`),
      {
        password
      },
      { merge: true }
    );
    displayPageAlert("Successfully generated a password!");
  } catch (error) {
    displayPageAlert(
      `An error occurred while generating a password: ${getFirestoreError(
        error as FirestoreError
      )}`
    );
  }
};

onUnmounted(async () => {
  const SettingsModule = useSettings();
  await SettingsModule.getSettings();
  await SettingsModule.getSitePrivateSettings();
});

const PagesModule = usePages();
const SettingsModule = useSettings();
SettingsModule.canSave = true;
PagesModule.viewPage("/external-services", "External Services", false);
</script>
