<template>
  <div id="settings">
    <v-row>
      <v-col cols="12" sm="6">
        <v-card color="card">
          <v-card-title class="cardtext--text">Site Settings</v-card-title>
          <v-card-text class="cardtext--text">
            <p>
              Fields with a <v-icon>mdi-lock</v-icon> are only visible to site
              members.
            </p>
            <v-text-field
              v-model="privateSettings.meetLink"
              label="Meeting Link"
              color="secondary"
              filled
              prepend-icon="mdi-lock"
            >
              <template #append>
                <v-tooltip bottom>
                  <template #activator="{ on }">
                    <v-btn
                      :aria-label="`${
                        privateSettings.linkHidden ? 'Show' : 'Hide'
                      } Meeting Link`"
                      icon
                      class="ml-auto"
                      v-on="on"
                      @click="
                        privateSettings.linkHidden = !privateSettings.linkHidden
                      "
                    >
                      <v-icon v-if="privateSettings.linkHidden"
                        >mdi-eye-off</v-icon
                      >
                      <v-icon v-else>mdi-eye</v-icon>
                    </v-btn>
                  </template>
                  {{ privateSettings.linkHidden ? "Show" : "Hide" }} Meeting
                  Link
                </v-tooltip>
              </template>
            </v-text-field>
            <v-text-field
              v-model="privateSettings.consoleURL"
              label="Admin Console URL"
              color="secondary"
              filled
              prepend-icon="mdi-lock"
            />
          </v-card-text>
        </v-card>
      </v-col>
      <v-col cols="12" sm="6">
        <v-card color="card">
          <v-card-title class="cardtext--text">Calendar Service</v-card-title>
          <v-card-text class="cardtext--text">
            <v-text-field
              v-model="settings.calURL"
              filled
              label="Script URL"
              hint="Copy and paste the script URL generated by Google Apps Script."
              color="secondary"
            />
            <v-select
              v-model="settings.calView"
              :items="permissions"
              filled
              label="Calendar Service View Permissions"
              hint="Choose who can view the calendar."
              persistent-hint
              color="secondary"
              item-color="secondary"
            />
            <v-btn
              block
              color="secondary"
              class="sectext--text"
              @click="generatePassword('apps-script-cal-view')"
            >
              Generate Password
            </v-btn>
            <v-spacer />
            <v-select
              v-model="settings.calEdit"
              :items="permissions"
              filled
              label="Calendar Service Edit Permissions"
              hint="Choose who can add, edit, and remove calendar events."
              persistent-hint
              color="secondary"
              item-color="secondary"
            />
            <v-btn
              block
              color="secondary"
              class="sectext--text"
              @click="generatePassword('apps-script-cal-edit')"
            >
              Generate Password
            </v-btn>
          </v-card-text>
        </v-card>
      </v-col>
      <v-col cols="12">
        <v-card color="card">
          <v-card-title class="cardtext--text">Email Service</v-card-title>
          <v-card-text class="cardtext--text">
            <v-text-field
              v-model="settings.mailURL"
              filled
              label="Script URL"
              hint="Copy and paste the URL generated by Google Apps Script."
              color="secondary"
            />
            <v-select
              v-model="settings.email"
              :items="permissions"
              filled
              label="Email Service Permissions"
              hint="Choose who can send emails through the website."
              persistent-hint
              color="secondary"
              item-color="secondary"
            />
            <v-btn
              block
              color="secondary"
              class="sectext--text"
              @click="generatePassword('apps-script-mail')"
            >
              Generate Password
            </v-btn>
            <v-spacer />
            <h3><v-icon>mdi-lock</v-icon> Group Email Addresses</h3>
            <v-spacer />
            <v-row v-if="privateSettings.addresses">
              <v-col
                v-for="(item, index) in privateSettings.addresses"
                :key="index"
                cols="12"
                md="6"
              >
                <v-card outlined class="mb-8">
                  <v-card-text class="cardtext--text">
                    <v-text-field
                      v-model="item.text"
                      :label="`Group ${index + 1} Name`"
                      filled
                      color="secondary"
                    />
                    <v-text-field
                      v-model="item.value"
                      :label="`Email Address ${index + 1}`"
                      filled
                      color="secondary"
                    />
                  </v-card-text>
                  <v-card-actions>
                    <v-tooltip bottom>
                      <template #activator="{ on }">
                        <v-btn
                          absolute
                          fab
                          small
                          bottom
                          right
                          color="error"
                          class="errtext--text"
                          v-on="on"
                          @click="removeEmailAddress(index)"
                        >
                          <v-icon>mdi-delete</v-icon>
                        </v-btn>
                      </template>
                      Delete Item
                    </v-tooltip>
                  </v-card-actions>
                </v-card>
              </v-col>
            </v-row>
            <v-btn
              color="secondary"
              class="sectext--text"
              @click="addEmailAddress"
              ><v-icon left>mdi-plus</v-icon> Add</v-btn
            >
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script lang="ts" setup>
import { usePages } from "@/store/pages";
import { useSettings } from "@/store/settings";
import { onUnmounted } from "@vue/composition-api";
import type { FirestoreError } from "firebase/firestore/lite";
import { displayPageAlert } from "@/plugins/errorHandler";
import { settings, privateSettings } from "@/plugins/routerStoreHelpers";
import { permissions } from "@/plugins/authHandler";

const save = async (
  callback: () => void,
  err = (e: FirestoreError) => {
    displayPageAlert(`An error occurred while saving: ${e.message}`);
  }
) => {
  try {
    const { firestore } = await import("@/plugins/firebase");
    const { doc, setDoc } = await import("firebase/firestore/lite");
    await setDoc(doc(firestore, "configuration/settings"), settings.value, {
      merge: true
    });
    await setDoc(
      doc(firestore, "configuration/priv-settings"),
      privateSettings.value,
      { merge: true }
    );
    callback();
  } catch (error) {
    err(error as FirestoreError);
  }
};

defineExpose({
  save
});

const addEmailAddress = () => {
  if (privateSettings.value.addresses) {
    privateSettings.value.addresses.push({
      text: "",
      value: ""
    });
  }
};

const removeEmailAddress = (index: number) => {
  if (privateSettings.value.addresses) {
    privateSettings.value.addresses.splice(index, 1);
  }
};

const generatePassword = async (type: string) => {
  try {
    const { generateString } = await import("@/plugins/stringGenerator");
    const password = generateString(20);
    const { firestore } = await import("@/plugins/firebase");
    const { doc, setDoc } = await import("firebase/firestore/lite");
    await setDoc(
      doc(firestore, `configuration/${type}`),
      {
        password
      },
      { merge: true }
    );
    displayPageAlert("Successfully generated a password!");
  } catch (error) {
    const rawError = error as FirestoreError;
    displayPageAlert(
      `An error occurred while generating a password: ${rawError.message}`
    );
  }
};

onUnmounted(async () => {
  const SettingsModule = useSettings();
  await SettingsModule.getSettings();
  await SettingsModule.getSitePrivateSettings();
});

const PagesModule = usePages();
const SettingsModule = useSettings();
SettingsModule.canSave = true;
PagesModule.viewPage("/settings", "Site Settings", false);
</script>
